version: "3"
services:
  poc-api:
    build: .
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8080:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8080",
        "--reload",
      ]
    environment:
      - TZ=Asia/Tokyo
      - LC_CTYPE=C.UTF-8
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - APP_CONFIG_FILE=local
      - WATCHFILES_FORCE_POLLING=true
    env_file:
      - ./app/config/local.env
    depends_on:
      - poc-db

  poc-db:
    image: postgres:14.1
    container_name: poc-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Test1234
      # TZ: "Asia/Tokyo"
    ports:
      - "5432:5432"
